/** A small but complete sample project (RTU, VAV, a fan, issues) for adapter and round-trip tests. */
import { emptyNaState, type AirflowRow, type Equipment, type Issue, type Project } from '../data/types';
import type { ProjectBundle } from '../workbook/adapter';

let n = 0;
const id = () => `00000000-0000-4000-8000-${String(++n).padStart(12, '0')}`;
const now = 1_790_000_000_000;

export function sampleBundle(): ProjectBundle {
  n = 0;
  const project: Project = {
    id: id(),
    name: 'Riverside Medical Office',
    scopeProfile: 'full',
    customScope: {},
    tolerance: 0.1,
    reportKind: 'prelim',
    info: {
      address: '1450 Riverside Dr, Sacramento, CA',
      architect: 'Lionakis',
      mechanicalEngineer: 'Capital Engineering',
      mechanicalContractor: 'Air Systems <North> Inc.',
      tabDate: '2026-09-15',
      technicians: 'J. Alvarez, M. Chen',
      projectManager: 'R. Singh',
      reportDate: '2026-09-23',
      narrative: 'Three RTUs and VAVs.\nAll balanced within ±10 %.',
    },
    blueprints: [{ sheet: 'M-101 Floor plan', revisionDate: '2026-06-12' }],
    naState: { sections: {}, fields: { electricalEngineer: { notation: 'N/A' } } },
    templateRevision: '05',
    createdAt: now,
    updatedAt: now,
  };
  const eq = (
    type: Equipment['type'],
    designation: string,
    slot: number,
    data: Equipment['data'],
    na = emptyNaState(),
  ): Equipment => ({
    id: id(),
    projectId: project.id,
    type,
    designation,
    slot,
    isExisting: false,
    data,
    naState: na,
    createdAt: now,
    updatedAt: now,
  });
  const rtu = eq(
    'rtu',
    'RTU-1',
    1,
    {
      areaServed: 'Lobby',
      location: 'Roof',
      manufacturer: 'Carrier',
      model: '48FC',
      hp: 3,
      unitEsp: 0.8,
      fanRpm: 1100,
      voltage: 460,
      phase: '3-phase',
      designTotalCfm: 1000,
      designOaCfm: 200,
      unitType: 'RTU',
      serial: '4719G',
      motorManufacturer: 'WEG',
      motorRpm: 1725,
      serviceFactor: 'SF 1.15',
      fla: 4.8,
      frame: '182T',
      volts1: 468,
      volts2: 465,
      volts3: 470,
      amps1: 3.9,
      amps2: 4.1,
      amps3: 4,
      driveType: 'Belt',
      motorSheave: '1VP44',
      fanPulley: 'AK74',
      belts: 'A42',
      cToC: '14 1/4',
      sheaveBore: '7/8 / 1',
      rotationDesign: 'CW',
      rotationActual: 'CW',
      hasFilters: 'Yes',
      filters: '2" pleated 16x20 x 4',
      finalSettings: 'Sheave 2.5 turns open',
      motorRpmFinal: 1742,
      fanRpmFinal: 1105,
      hasVfd: 'No',
      oaDamper: '35 % open',
      spEntering: -0.35,
      spLeaving1: -0.55,
      spLeaving3: -0.95,
      spLeaving4: -1.05,
      spLeaving5: 0.72,
      instrument: 'Flow Hood',
      remarks: 'Belt replaced.\nSecond remark line.',
    },
    { sections: {}, fields: { fla: { notation: 'Not Avail.' } } },
  );
  delete rtu.data.fla; // FLA marked Not Avail. instead
  const vav = eq('vav', 'VAV-101', 1, {
    areaServed: 'Suite 101',
    location: 'Ceiling',
    manufacturer: 'Titus',
    model: 'DESV',
    inletSize: 8,
    terminalType: 'Pressure Independent',
    designMaxCfm: 400,
    designMinCfm: 150,
    ddcAddress: 'AV-101',
    serial: 'T-7788',
    calibrationFactor: 1.02,
    ddcMaxMin: '400 / 150',
    minCfmActual: 155,
    instrument: 'Flow Hood',
  });
  const fan = eq('fan', 'EF-1', 3, { areaServed: 'Restrooms', unitType: 'EF' });
  const row = (
    e: Equipment,
    table: string,
    order: number,
    data: AirflowRow['data'],
    na: AirflowRow['na'] = {},
  ): AirflowRow => ({
    id: id(),
    projectId: project.id,
    equipmentId: e.id,
    table,
    order,
    data,
    na,
    createdAt: now,
    updatedAt: now,
  });
  const rows = [
    row(rtu, 'supply', 1, {
      no: 'S-1',
      area: 'Lobby',
      type: 'CD',
      size: '24x24',
      ak: 1,
      designCfm: 500,
      initialVel: 480,
      finalVel: 505,
    }),
    row(rtu, 'supply', 2, {
      no: 'S-2',
      area: 'Lobby',
      type: 'CD',
      size: '24x24',
      ak: 1,
      designCfm: 500,
      finalVel: 470,
    }),
    row(
      rtu,
      'oa',
      1,
      { no: 'OA-1', area: 'Hood', type: 'OA', size: '36x18', ak: 4.5, designCfm: 200 },
      { finalVel: { notation: 'Not Acc.' } },
    ),
    row(vav, 'outlets', 1, {
      no: '1',
      area: 'Suite 101',
      type: 'CD',
      size: '12x12',
      ak: 1,
      designCfm: 200,
      finalVel: 195,
    }),
    row(vav, 'outlets', 2, {
      no: '2',
      area: 'Suite 101',
      type: 'CD',
      size: '12x12',
      ak: 1,
      designCfm: 200,
      finalVel: 210,
    }),
  ];
  const issue = (
    kind: Issue['kind'],
    number: number,
    remark: string,
    equipmentId: string | null,
    status: Issue['status'] = 'Open',
  ): Issue => ({
    id: id(),
    projectId: project.id,
    kind,
    number,
    remark,
    status,
    comments: '',
    equipmentId,
    createdAt: now,
    updatedAt: now,
  });
  const issues = [
    issue('new', 1, 'belt worn; replaced during TAB.', rtu.id, 'Closed'),
    issue('new', 2, 'Ceiling access blocked at corridor.', null),
    issue('existing', 1, 'damper actuator seized.', vav.id),
  ];
  const instruments = [
    {
      id: id(),
      projectId: project.id,
      order: 0,
      type: 'Balometer',
      manufacturer: 'Evergreen Telemetry',
      model: 'Three Pounder',
      serial: '2400180B',
      calibrationDate: '2026-03-14',
      createdAt: now,
      updatedAt: now,
    },
  ];
  return { project, equipment: [rtu, vav, fan], rows, issues, instruments };
}
